"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import dayjs, { Dayjs } from "dayjs";
import { Alert, Box, Button, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, MenuItem, Paper, Stack, TextField, Typography, useTheme } from "@mui/material";
import AddRoundedIcon from "@mui/icons-material/AddRounded";
import ChevronLeftRoundedIcon from "@mui/icons-material/ChevronLeftRounded";
import ChevronRightRoundedIcon from "@mui/icons-material/ChevronRightRounded";
import CalendarMonthRoundedIcon from "@mui/icons-material/CalendarMonthRounded";
import DeleteOutlineRoundedIcon from "@mui/icons-material/DeleteOutlineRounded";
import EditRoundedIcon from "@mui/icons-material/EditRounded";
import { authenticatedFetch, getApiUrl } from "../../apiUrl";

type CalendarEvent = { id:string; title:string; description:string; event_type:string; starts_at:string; ends_at:string|null; color:string };
const TYPES = [{value:"event",label:"Event",color:"#3b82f6"},{value:"meeting",label:"Meeting",color:"#8b5cf6"},{value:"deadline",label:"Deadline",color:"#f59e0b"},{value:"urgent",label:"Urgent",color:"#ef4444"}];
const emptyForm = { id:"", title:"", description:"", eventType:"event", date:dayjs().format("YYYY-MM-DD"), startTime:"09:00", endTime:"10:00" };

export default function CalendarPage(){
  const theme=useTheme(); const datePickerRef=useRef<HTMLInputElement|null>(null); const [month,setMonth]=useState(dayjs().startOf("month")); const [selectedDate,setSelectedDate]=useState(dayjs()); const [events,setEvents]=useState<CalendarEvent[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [dialog,setDialog]=useState(false); const [form,setForm]=useState(emptyForm); const [error,setError]=useState("");
  const load=async()=>{setLoading(true);try{const r=await authenticatedFetch(getApiUrl("calendar-events"));if(!r.ok)throw new Error();setEvents(await r.json())}catch{setError("Unable to load calendar events.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const days=useMemo(()=>{const start=month.startOf("month").startOf("week");return Array.from({length:42},(_,i)=>start.add(i,"day"))},[month]);
  const openNew=(date:Dayjs=dayjs())=>{setForm({...emptyForm,date:date.format("YYYY-MM-DD")});setError("");setDialog(true)};
  const openEdit=(event:CalendarEvent)=>{setForm({id:event.id,title:event.title,description:event.description||"",eventType:event.event_type,date:dayjs(event.starts_at).format("YYYY-MM-DD"),startTime:dayjs(event.starts_at).format("HH:mm"),endTime:event.ends_at?dayjs(event.ends_at).format("HH:mm"):""});setError("");setDialog(true)};
  const save=async()=>{if(!form.title.trim()){setError("Title is required.");return}setSaving(true);setError("");try{const type=TYPES.find(x=>x.value===form.eventType)!;const body={id:form.id,title:form.title,description:form.description,eventType:form.eventType,startsAt:dayjs(`${form.date}T${form.startTime}`).toISOString(),endsAt:form.endTime?dayjs(`${form.date}T${form.endTime}`).toISOString():null,color:type.color};const r=await authenticatedFetch(getApiUrl("calendar-events"),{method:form.id?"PUT":"POST",body:JSON.stringify(body)});if(!r.ok)throw new Error((await r.json()).error);setDialog(false);await load()}catch(e:any){setError(e.message||"Unable to save event.")}finally{setSaving(false)}};
  const remove=async()=>{if(!form.id)return;setSaving(true);try{await authenticatedFetch(`${getApiUrl("calendar-events")}?id=${form.id}`,{method:"DELETE"});setDialog(false);await load()}catch{setError("Unable to delete event.")}finally{setSaving(false)}};
  const upcoming=events.filter(e=>dayjs(e.starts_at).isAfter(dayjs().subtract(1,"minute"))).slice(0,5);
  return <Box sx={{p:{xs:2,md:4},maxWidth:1500,mx:"auto",width:"100%"}}>
    <Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between" gap={2} mb={3}><Box><Typography variant="h4" fontWeight={900}>Calendar & Deadlines</Typography><Typography color="text.secondary">Keep meetings, events and deadlines organized.</Typography></Box><Button variant="contained" startIcon={<AddRoundedIcon/>} onClick={()=>openNew()} sx={{alignSelf:{xs:"stretch",sm:"center"}}}>New event</Button></Stack>
    {error&&!dialog&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}
    <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",lg:"minmax(0,1fr) 320px"},gap:3}}>
      <Paper sx={{overflow:"hidden",border:`1px solid ${theme.palette.divider}`,boxShadow:"none"}}><Stack direction="row" alignItems="center" justifyContent="space-between" p={2} borderBottom={`1px solid ${theme.palette.divider}`}><Stack direction="row" alignItems="center" gap={1}><IconButton onClick={()=>setMonth(x=>x.subtract(1,"month"))}><ChevronLeftRoundedIcon/></IconButton><Box sx={{position:"relative"}}><Button onClick={()=>{const input=datePickerRef.current;if(input&&typeof input.showPicker==="function")input.showPicker();else{const today=dayjs();setSelectedDate(today);setMonth(today.startOf("month"));}}}>Today</Button><Box component="input" ref={datePickerRef} type="date" value={selectedDate.format("YYYY-MM-DD")} aria-label="Choose calendar date" onChange={(event:React.ChangeEvent<HTMLInputElement>)=>{const picked=dayjs(event.target.value);if(picked.isValid()){setSelectedDate(picked);setMonth(picked.startOf("month"));}}} sx={{position:"absolute",width:1,height:1,opacity:0,pointerEvents:"none",bottom:0,left:"50%"}}/></Box><IconButton onClick={()=>setMonth(x=>x.add(1,"month"))}><ChevronRightRoundedIcon/></IconButton></Stack><Typography fontWeight={900} fontSize={{xs:16,sm:20}}>{month.format("MMMM YYYY")}</Typography></Stack>
        {loading?<Box sx={{height:520,display:"grid",placeItems:"center"}}><CircularProgress/></Box>:<Box sx={{display:"grid",gridTemplateColumns:"repeat(7,minmax(90px,1fr))",overflowX:"auto"}}>{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><Box key={x} sx={{p:1,textAlign:"center",fontWeight:800,fontSize:12,color:"text.secondary",borderBottom:`1px solid ${theme.palette.divider}`}}>{x}</Box>)}{days.map(day=>{const dayEvents=events.filter(e=>dayjs(e.starts_at).isSame(day,"day"));return <Box key={day.toString()} onDoubleClick={()=>openNew(day)} sx={{minHeight:{xs:105,md:125},p:1,borderRight:`1px solid ${theme.palette.divider}`,borderBottom:`1px solid ${theme.palette.divider}`,bgcolor:day.month()===month.month()?"background.paper":"action.hover",cursor:"pointer","&:hover":{bgcolor:"action.hover"}}}><Typography sx={{width:28,height:28,display:"grid",placeItems:"center",borderRadius:"50%",fontSize:12,fontWeight:day.isSame(dayjs(),"day")?900:600,bgcolor:day.isSame(dayjs(),"day")?"primary.main":"transparent",color:day.isSame(dayjs(),"day")?"primary.contrastText":"text.primary"}}>{day.date()}</Typography><Stack gap={.5} mt={.5}>{dayEvents.slice(0,3).map(e=><Box key={e.id} onClick={x=>{x.stopPropagation();openEdit(e)}} sx={{px:.7,py:.45,borderRadius:1,bgcolor:`${e.color}20`,borderLeft:`3px solid ${e.color}`,fontSize:10,fontWeight:800,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{dayjs(e.starts_at).format("HH:mm")} {e.title}</Box>)}{dayEvents.length>3&&<Typography fontSize={10} color="text.secondary">+{dayEvents.length-3} more</Typography>}</Stack></Box>})}</Box>}
      </Paper>
      <Stack gap={2}><Paper sx={{p:2.5,border:`1px solid ${theme.palette.divider}`,boxShadow:"none"}}><Stack direction="row" gap={1} alignItems="center" mb={2}><CalendarMonthRoundedIcon color="primary"/><Typography fontWeight={900}>Upcoming</Typography></Stack>{upcoming.length?<Stack gap={1.2}>{upcoming.map(e=><Box key={e.id} onClick={()=>openEdit(e)} sx={{p:1.4,borderRadius:2,bgcolor:"action.hover",borderLeft:`4px solid ${e.color}`,cursor:"pointer"}}><Typography fontWeight={800} fontSize={13}>{e.title}</Typography><Typography fontSize={11} color="text.secondary">{dayjs(e.starts_at).format("ddd, DD MMM · HH:mm")}</Typography><Chip label={e.event_type} size="small" sx={{mt:.8,height:21,textTransform:"capitalize"}}/></Box>)}</Stack>:<Box textAlign="center" py={5}><CalendarMonthRoundedIcon sx={{fontSize:42,color:"text.disabled"}}/><Typography fontWeight={800}>No events scheduled</Typography><Button onClick={()=>openNew()} sx={{mt:1}}>Add your first event</Button></Box>}</Paper></Stack>
    </Box>
    <Dialog open={dialog} onClose={()=>!saving&&setDialog(false)} fullWidth maxWidth="sm"><DialogTitle sx={{fontWeight:900}}>{form.id?"Edit event":"Create event"}</DialogTitle><DialogContent sx={{display:"grid",gap:2,pt:"12px!important"}}>{error&&<Alert severity="error">{error}</Alert>}<TextField label="Title" required value={form.title} onChange={e=>setForm(x=>({...x,title:e.target.value}))}/><TextField label="Type" select value={form.eventType} onChange={e=>setForm(x=>({...x,eventType:e.target.value}))}>{TYPES.map(x=><MenuItem key={x.value} value={x.value}><Stack direction="row" gap={1} alignItems="center"><Box sx={{width:9,height:9,borderRadius:"50%",bgcolor:x.color}}/>{x.label}</Stack></MenuItem>)}</TextField><TextField label="Description" multiline minRows={3} value={form.description} onChange={e=>setForm(x=>({...x,description:e.target.value}))}/><TextField label="Date" type="date" value={form.date} onChange={e=>setForm(x=>({...x,date:e.target.value}))} slotProps={{inputLabel:{shrink:true}}}/><Stack direction={{xs:"column",sm:"row"}} gap={2}><TextField fullWidth label="Start time" type="time" value={form.startTime} onChange={e=>setForm(x=>({...x,startTime:e.target.value}))} slotProps={{inputLabel:{shrink:true}}}/><TextField fullWidth label="End time" type="time" value={form.endTime} onChange={e=>setForm(x=>({...x,endTime:e.target.value}))} slotProps={{inputLabel:{shrink:true}}}/></Stack></DialogContent><DialogActions sx={{p:2}}>{form.id&&<Button color="error" startIcon={<DeleteOutlineRoundedIcon/>} onClick={remove} disabled={saving}>Delete</Button>}<Box flex={1}/><Button onClick={()=>setDialog(false)} disabled={saving}>Cancel</Button><Button variant="contained" startIcon={saving?<CircularProgress size={16}/>:form.id?<EditRoundedIcon/>:<AddRoundedIcon/>} onClick={save} disabled={saving}>{saving?"Saving...":form.id?"Save changes":"Create event"}</Button></DialogActions></Dialog>
  </Box>
}
