import { createHmac, randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { getAuthenticatedUser, pool, SECRET_KEY } from "../_lib/server";
import { isSafePublicHttpsUrl } from "../_lib/security";
async function ensure(){await pool.query(`CREATE TABLE IF NOT EXISTS integration_webhooks(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,name TEXT NOT NULL,url TEXT NOT NULL,events JSONB NOT NULL DEFAULT '[]'::jsonb,active BOOLEAN DEFAULT TRUE,last_status INTEGER,last_delivery_at TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT NOW())`)}
const secret=id=>createHmac("sha256",SECRET_KEY).update(`smart-manage-webhook:${id}`).digest("hex");
export async function GET(req){const u=getAuthenticatedUser(req);if(!u?.id)return NextResponse.json({error:"Unauthorized"},{status:401});await ensure();const r=await pool.query("SELECT id,name,url,events,active,last_status,last_delivery_at,created_at FROM integration_webhooks WHERE user_id=$1 ORDER BY created_at DESC",[String(u.id)]);return NextResponse.json(r.rows)}
export async function POST(req){const u=getAuthenticatedUser(req);if(!u?.id)return NextResponse.json({error:"Unauthorized"},{status:401});await ensure();const b=await req.json();if(!String(b.name||'').trim()||!isSafePublicHttpsUrl(b.url))return NextResponse.json({error:"A name and public HTTPS URL are required"},{status:400});const id=randomUUID(),events=Array.isArray(b.events)?b.events.slice(0,20):['board.updated'];await pool.query("INSERT INTO integration_webhooks(id,user_id,name,url,events) VALUES($1,$2,$3,$4,$5::jsonb)",[id,String(u.id),String(b.name).trim().slice(0,100),b.url,JSON.stringify(events)]);return NextResponse.json({id,signingSecret:secret(id)},{status:201})}
export async function DELETE(req){const u=getAuthenticatedUser(req);if(!u?.id)return NextResponse.json({error:"Unauthorized"},{status:401});await ensure();await pool.query("DELETE FROM integration_webhooks WHERE id=$1 AND user_id=$2",[new URL(req.url).searchParams.get('id'),String(u.id)]);return NextResponse.json({success:true})}
