"use client";
import { Box, Chip, Stack, Typography } from "@mui/material";
import CalendarMonthRounded from "@mui/icons-material/CalendarMonthRounded";
import TaskAltRounded from "@mui/icons-material/TaskAltRounded";
import InsertChartRounded from "@mui/icons-material/InsertChartRounded";
import HomeRounded from "@mui/icons-material/HomeRounded";
import FolderRounded from "@mui/icons-material/FolderRounded";

const P = "#6D4AFF";
const card = { bgcolor: "#fff", border: "1px solid #EAECF0", borderRadius: 3, boxShadow: "0 18px 50px rgba(16,24,40,.10)" };

export function PhoneMockup() {
  return <Box sx={{ position:"relative", width:"100%", height:{xs:520,md:600}, background:"radial-gradient(circle,rgba(109,74,255,.18),transparent 66%)" }}>
    <Box sx={{ position:"absolute", left:"50%", top:"50%", width:{xs:245,md:285}, height:{xs:485,md:560}, transform:"translate(-50%,-50%) rotate(7deg)", bgcolor:"#080A12", borderRadius:"46px", p:"9px", boxShadow:"0 35px 70px rgba(16,24,40,.3)" }}>
      <Box sx={{height:"100%",borderRadius:"38px",overflow:"hidden",bgcolor:"#f8fafc",position:"relative"}}><Box sx={{position:"absolute",top:9,left:"50%",transform:"translateX(-50%)",width:82,height:23,borderRadius:20,bgcolor:"#080A12",zIndex:2}}/><Box sx={{background:"linear-gradient(135deg,#6D4AFF,#4F46E5)",color:"#fff",p:2.3,pt:5}}><Typography sx={{fontSize:10,opacity:.8}}>Hello, Argjend</Typography><Typography sx={{fontSize:22,fontWeight:900}}>Dashboard</Typography></Box><Box sx={{p:1.5}}><Box sx={{...card,p:1.3,boxShadow:"0 5px 18px rgba(16,24,40,.06)"}}><Typography sx={{fontSize:9,fontWeight:800,mb:1}}>Overview</Typography><Box sx={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:.6}}>{[["Projects","24"],["Tasks","128"],["Completed","76%"]].map(x=><Box key={x[0]} sx={{bgcolor:"#fafafa",p:.8,borderRadius:1.5}}><Typography sx={{fontSize:7,color:"#667085"}}>{x[0]}</Typography><Typography sx={{fontSize:15,fontWeight:900}}>{x[1]}</Typography><Typography sx={{fontSize:6,color:"#22c55e"}}>↑ 12%</Typography></Box>)}</Box></Box><Box sx={{...card,p:1.3,mt:1.1,boxShadow:"0 5px 18px rgba(16,24,40,.06)"}}><Typography sx={{fontSize:9,fontWeight:800,mb:.6}}>Recent Projects</Typography>{["Website Redesign","Mobile App","Marketing Campaign"].map((x,i)=><Stack key={x} direction="row" justifyContent="space-between" sx={{py:.65,borderTop:i?"1px solid #f1f5f9":0}}><Typography sx={{fontSize:7.5,fontWeight:700}}>{x}</Typography><Typography sx={{fontSize:6.5,color:[P,"#f59e0b","#22c55e"][i]}}>{["In Progress","Review","Completed"][i]}</Typography></Stack>)}</Box><Box sx={{...card,p:1.3,mt:1.1,boxShadow:"0 5px 18px rgba(16,24,40,.06)"}}><Typography sx={{fontSize:9,fontWeight:800}}>Upcoming Events</Typography><Stack direction="row" justifyContent="space-between" sx={{mt:1}}>{["22","23","24","25","26"].map((x,i)=><Box key={x} sx={{p:.65,borderRadius:1,bgcolor:i===1?P:"transparent",color:i===1?"#fff":"#101828",fontSize:8}}>{x}</Box>)}</Stack></Box></Box><Stack direction="row" justifyContent="space-around" sx={{position:"absolute",bottom:0,left:0,right:0,p:1.2,bgcolor:"#fff",borderTop:"1px solid #EAECF0",color:"#98A2B3"}}><HomeRounded sx={{fontSize:17,color:P}}/><FolderRounded sx={{fontSize:17}}/><TaskAltRounded sx={{fontSize:17}}/><CalendarMonthRounded sx={{fontSize:17}}/></Stack></Box>
    </Box>
    <FloatCard sx={{left:{xs:0,md:-10},top:{xs:55,md:80}}} icon={<CalendarMonthRounded/>} title="Calendar" text="Upcoming events and deadlines" accent="3 Events today" />
    <FloatCard sx={{left:{xs:15,md:25},bottom:{xs:25,md:30}}} icon={<InsertChartRounded/>} title="Reports" text="Track progress and performance" accent="View insights →" chart />
    <FloatCard sx={{right:{xs:-5,md:-20},top:{xs:160,md:180}}} icon={<TaskAltRounded/>} title="Tasks" text="128 tasks this week" accent="76% Completed" progress />
  </Box>
}

function FloatCard({sx,icon,title,text,accent,progress,chart}:{sx:any;icon:React.ReactNode;title:string;text:string;accent:string;progress?:boolean;chart?:boolean}) { return <Box sx={{...card,position:"absolute",zIndex:3,width:{xs:125,md:150},p:1.7,...sx,"@keyframes floaty":{from:{transform:"translateY(0)"},to:{transform:"translateY(-7px)"}},animation:"floaty 3s ease-in-out infinite alternate"}}><Box sx={{width:29,height:29,borderRadius:1.5,bgcolor:"#F0ECFF",color:P,display:"grid",placeItems:"center","& svg":{fontSize:17}}}>{icon}</Box><Typography sx={{fontSize:11,fontWeight:900,mt:1}}>{title}</Typography><Typography sx={{fontSize:8,color:"#667085",my:.5}}>{text}</Typography>{progress&&<Box sx={{height:5,bgcolor:"#E9E5FF",borderRadius:5,my:.7}}><Box sx={{width:"76%",height:"100%",bgcolor:P,borderRadius:5}}/></Box>}{chart&&<Stack direction="row" alignItems="end" spacing={.35} sx={{height:24,my:.5}}>{[35,60,42,78,55,90].map((h,i)=><Box key={i} sx={{flex:1,height:h+"%",bgcolor:i===5?P:"#C7BFFF",borderRadius:"2px 2px 0 0"}}/>)}</Stack>}<Typography sx={{fontSize:8,color:P,fontWeight:800}}>{accent}</Typography></Box> }

export function LaptopPreview(){return <Box sx={{position:"relative",height:{xs:300,md:390},display:"grid",placeItems:"center"}}><Box sx={{width:"88%",bgcolor:"#111827",borderRadius:"16px 16px 4px 4px",p:"9px",boxShadow:"0 24px 50px rgba(16,24,40,.18)"}}><Box sx={{bgcolor:"#fff",borderRadius:1.5,p:2}}><Box sx={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:1}}>{[["Total Projects","124"],["Tasks","128"],["Completed","76%"]].map(x=><Box key={x[0]} sx={{p:1.2,border:"1px solid #EAECF0",borderRadius:2}}><Typography sx={{fontSize:7,color:"#667085"}}>{x[0]}</Typography><Typography sx={{fontSize:17,fontWeight:900}}>{x[1]}</Typography></Box>)}</Box><Box sx={{display:"grid",gridTemplateColumns:"1.5fr .7fr",gap:1,mt:1}}><Box sx={{height:100,border:"1px solid #EAECF0",borderRadius:2,p:1}}><Typography sx={{fontSize:8,fontWeight:800}}>Project Progress</Typography><Stack direction="row" alignItems="end" spacing={.5} sx={{height:72}}>{[25,45,32,65,42,74,55,88].map((h,i)=><Box key={i} sx={{flex:1,height:h+"%",bgcolor:i===7?P:"#DDD6FE",borderRadius:"3px 3px 0 0"}}/>)}</Stack></Box><Box sx={{border:"1px solid #EAECF0",borderRadius:2,p:1,display:"grid",placeItems:"center"}}><Box sx={{width:64,height:64,borderRadius:"50%",background:"conic-gradient(#22c55e 0 60%,#6D4AFF 60% 82%,#F59E0B 82%)",position:"relative","&:after":{content:'""',position:"absolute",inset:12,borderRadius:"50%",bgcolor:"#fff"}}}/></Box></Box></Box></Box><Box sx={{width:"96%",height:10,bgcolor:"#d5d8df",borderRadius:"0 0 50% 50%"}}/></Box>}

export function AboutVisual(){return <Box sx={{position:"relative",height:{xs:360,md:430}}}><Box sx={{...card,p:2,position:"absolute",left:0,top:20,width:"52%"}}><Typography fontWeight={900} fontSize={12}>Team Activity</Typography>{["Updated report","Completed task","Uploaded file","Created a project"].map((x,i)=><Stack key={x} direction="row" spacing={1} sx={{py:.75}}><Box sx={{width:20,height:20,borderRadius:"50%",bgcolor:["#DDD6FE","#D1FAE5","#DBEAFE","#FFEDD5"][i]}}/><Typography sx={{fontSize:8}}>{x}</Typography></Stack>)}</Box><Box sx={{...card,p:2,position:"absolute",right:5,top:80,width:"46%"}}><Typography fontWeight={900} fontSize={11}>May 2026</Typography><Box sx={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:.7,mt:1}}>{Array.from({length:28},(_,i)=><Box key={i} sx={{fontSize:7,textAlign:"center",p:.45,borderRadius:1,bgcolor:i===16?P:"transparent",color:i===16?"#fff":"#667085"}}>{i+1}</Box>)}</Box></Box><Box sx={{...card,p:2,position:"absolute",left:45,bottom:5,width:"42%"}}><Typography fontWeight={900} fontSize={11}>Weekly Progress</Typography><Typography sx={{color:"#22c55e",fontSize:22,fontWeight:900}}>+18%</Typography><Stack direction="row" alignItems="end" spacing={.5} sx={{height:45}}>{[30,55,42,72,65,90].map((h,i)=><Box key={i} sx={{flex:1,height:h+"%",bgcolor:"#34D399",borderRadius:"2px 2px 0 0"}}/>)}</Stack></Box></Box>}

export function MapVisual(){return <Box sx={{height:"100%",minHeight:330,borderRadius:3,overflow:"hidden",position:"relative",background:"linear-gradient(30deg,#eef2f6 12%,transparent 12.5%,transparent 87%,#eef2f6 87.5%),linear-gradient(150deg,#eef2f6 12%,transparent 12.5%,transparent 87%,#eef2f6 87.5%),#f8fafc",backgroundSize:"70px 120px",border:"1px solid #EAECF0"}}><Box component="a" href="https://maps.app.goo.gl/nsezqqpsuNS3Enxp6" target="_blank" rel="noopener noreferrer" aria-label="Open Smart Manage location in Google Maps" sx={{position:"absolute",left:"55%",top:"42%",width:18,height:18,bgcolor:P,borderRadius:"50% 50% 50% 0",transform:"rotate(-45deg)",boxShadow:"0 5px 15px rgba(109,74,255,.35)"}}/><Box sx={{...card,position:"absolute",right:15,bottom:15,left:15,p:2}}><Typography fontWeight={900}>Smart Manage HQ</Typography><Typography component="a" href="https://maps.app.goo.gl/nsezqqpsuNS3Enxp6" target="_blank" rel="noopener noreferrer" sx={{display:"block",fontSize:12,color:P,mt:.7,textDecoration:"none",fontWeight:700}}>Location · Open in Google Maps</Typography><Typography component="a" href="mailto:aximostudioo@gmail.com" sx={{display:"block",fontSize:12,color:"#667085",textDecoration:"none"}}>Email · aximostudioo@gmail.com</Typography><Typography component="a" href="tel:+38343882536" sx={{display:"block",fontSize:12,color:"#667085",textDecoration:"none"}}>Phone · +383 43 882 536</Typography><Typography sx={{fontSize:12,color:"#667085"}}>Mon – Fri · 09:00 – 18:00</Typography></Box></Box>}
