
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


import ThemeRegistry from "./ThemeRegistry";
import Sidebar from "./Sidebar";
import TopBar from "./TopBar";
import Box from "@mui/material/Box";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeRegistry>
          <Box sx={{ display: 'flex', minHeight: '100vh', width: '100vw', bgcolor: '#f6f7fb' }}>
            <Sidebar />
            <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
              <TopBar />
              <Box component="main" sx={{ flex: 1, p: '32px 32px 0 32px', bgcolor: '#f6f7fb' }}>{children}</Box>
            </Box>
          </Box>
        </ThemeRegistry>
      </body>
    </html>
  );
}
