"use client";
import { Avatar, AvatarGroup, Box, Chip, Stack, Typography } from "@mui/material";
import CheckCircleRoundedIcon from "@mui/icons-material/CheckCircleRounded";
import TaskAltRoundedIcon from "@mui/icons-material/TaskAltRounded";

const card = { bgcolor: "#fff", border: "1px solid #EAECF0", borderRadius: 3, boxShadow: "0 16px 38px rgba(74,58,140,.10)" };
const activities = [["Arben","updated a report","2 min ago","#6D4AFF"],["Drita","completed a task","15 min ago","#22C55E"],["Blend","uploaded a file","28 min ago","#3B82F6"],["You","created a project","1 hour ago","#F59E0B"]];

export default function PolishedAboutVisual(){return <Box sx={{position:"relative",height:{xs:500,sm:430},maxWidth:590,mx:"auto",width:"100%"}}>
  <Box sx={{...card,p:2,position:"absolute",left:0,top:5,width:{xs:"72%",sm:"55%"},zIndex:2}}><Typography fontWeight={800} fontSize={12} mb={1}>Team Activity</Typography>{activities.map(([name,action,time,color])=><Stack key={name} direction="row" alignItems="center" spacing={1} sx={{py:.7}}><Avatar sx={{width:25,height:25,fontSize:9,fontWeight:800,bgcolor:color}}>{name[0]}</Avatar><Box sx={{minWidth:0,flex:1}}><Typography noWrap sx={{fontSize:9,fontWeight:700}}>{name} {action}</Typography><Typography sx={{fontSize:7.5,color:"#98A2B3"}}>{time}</Typography></Box><CheckCircleRoundedIcon sx={{fontSize:14,color}}/></Stack>)}</Box>
  <Box sx={{...card,p:2,position:"absolute",right:0,top:{xs:150,sm:62},width:{xs:"68%",sm:"48%"}}}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800} fontSize={11}>July 2026</Typography><Typography fontSize={8} color="#6D4AFF" fontWeight={800}>3 events today</Typography></Stack><Box sx={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:.65,mt:1}}>{Array.from({length:28},(_,i)=><Box key={i} sx={{fontSize:7,textAlign:"center",p:.5,borderRadius:1,bgcolor:i===11?"#6D4AFF":"transparent",color:i===11?"#fff":"#667085",position:"relative"}}>{i+1}{[4,11,18].includes(i)&&<Box sx={{position:"absolute",width:3,height:3,borderRadius:"50%",bgcolor:i===11?"#fff":"#22C55E",bottom:1,left:"50%"}}/>}</Box>)}</Box><Box sx={{mt:1,p:.8,borderRadius:1.5,bgcolor:"#F0ECFF",borderLeft:"3px solid #6D4AFF"}}><Typography sx={{fontSize:8,fontWeight:800}}>Team planning · 14:00</Typography></Box></Box>
  <Box sx={{...card,p:2,position:"absolute",left:{xs:0,sm:35},bottom:{xs:25,sm:0},width:{xs:"58%",sm:"42%"}}}><Stack direction="row" justifyContent="space-between"><Box><Typography fontWeight={800} fontSize={10}>Weekly Progress</Typography><Typography sx={{fontSize:8,color:"#667085"}}>Productivity</Typography></Box><Typography sx={{color:"#22C55E",fontSize:20,fontWeight:900}}>+18%</Typography></Stack><Stack direction="row" alignItems="end" spacing={.5} sx={{height:42,my:.8}}>{[34,55,46,70,64,84].map((h,i)=><Box key={i} sx={{flex:1,height:h+"%",bgcolor:i===5?"#22C55E":"#A7F3D0",borderRadius:"2px 2px 0 0"}}/>)}</Stack><Typography sx={{fontSize:8,color:"#667085"}}><b>84% completed</b> · vs last week</Typography></Box>
  <Box sx={{...card,p:2,position:"absolute",right:{xs:0,sm:10},bottom:{xs:0,sm:12},width:{xs:"62%",sm:"46%"},zIndex:3}}><Stack direction="row" justifyContent="space-between" alignItems="center"><TaskAltRoundedIcon sx={{color:"#6D4AFF",fontSize:18}}/><Chip label="In Progress" size="small" sx={{height:20,fontSize:7,bgcolor:"#F0ECFF",color:"#6D4AFF",fontWeight:800}}/></Stack><Typography sx={{fontSize:10,fontWeight:800,mt:1}}>Design new landing page</Typography><Typography sx={{fontSize:8,color:"#98A2B3",my:.8}}>Jul 18, 2026</Typography><Box sx={{height:4,borderRadius:4,bgcolor:"#E9E5FF"}}><Box sx={{height:"100%",width:"68%",borderRadius:4,bgcolor:"#6D4AFF"}}/></Box><AvatarGroup max={3} sx={{justifyContent:"flex-end",mt:1,"& .MuiAvatar-root":{width:20,height:20,fontSize:7}}}><Avatar sx={{bgcolor:"#6D4AFF"}}>A</Avatar><Avatar sx={{bgcolor:"#22C55E"}}>D</Avatar><Avatar sx={{bgcolor:"#F59E0B"}}>B</Avatar></AvatarGroup></Box>
</Box>}
