"use client";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Box, Button, Card, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, MenuItem, Select, Stack, TextField, Typography } from "@mui/material";
import ReceiptLongRoundedIcon from "@mui/icons-material/ReceiptLongRounded";
import { useSearchParams } from "next/navigation";
import { authenticatedFetch, getApiUrl } from "../../apiUrl";

type Invoice={id:string;invoice_number:string;client_name:string;issue_date:string;due_date:string;currency:string;subtotal:number;tax_rate:number;tax_amount:number;total:number;status:string;notes?:string;line_items:any[];branding:any;pdf_file_id?:string;created_by_name?:string};
const statuses=["","DRAFT","SENT","PAID","OVERDUE","CANCELLED"];
const money=(value:number,currency:string)=>new Intl.NumberFormat(undefined,{style:"currency",currency:currency||"EUR"}).format(Number(value||0));

export default function InvoicesPage(){
 const workspaceId=useSearchParams().get("id")||""; const[rows,setRows]=useState<Invoice[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[search,setSearch]=useState("");const[status,setStatus]=useState("");const[selected,setSelected]=useState<Invoice|null>(null);
 const load=useCallback(async()=>{if(!workspaceId){setError("Select a workspace to view invoices.");setLoading(false);return}setLoading(true);setError("");try{const q=new URLSearchParams({workspaceId});if(search)q.set("search",search);if(status)q.set("status",status);const r=await authenticatedFetch(getApiUrl(`/invoices?${q}`),{suppressNativeErrorAlert:true});if(!r.ok)throw new Error("Unable to load invoices");setRows((await r.json()).invoices||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}},[workspaceId,search,status]);
 useEffect(()=>{const id=setTimeout(()=>void load(),200);return()=>clearTimeout(id)},[load]);
 const update=async(next:string)=>{if(!selected)return;const r=await authenticatedFetch(getApiUrl(`/invoices/${selected.id}`),{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:next})});if(!r.ok)return setError("Unable to update invoice status");const invoice=(await r.json()).invoice;setSelected(invoice);setRows(x=>x.map(v=>v.id===invoice.id?invoice:v))};
 const duplicate=async(invoice:Invoice)=>{const r=await authenticatedFetch(getApiUrl(`/invoices/${invoice.id}/duplicate`),{method:"POST"});if(!r.ok)return setError("Unable to duplicate invoice");const copy=(await r.json()).invoice;setRows(x=>[copy,...x]);setSelected(copy)};
 const sorted=useMemo(()=>rows,[rows]);
 return <Box sx={{maxWidth:1280,mx:"auto",px:{xs:1.5,md:4},py:{xs:2,md:4},pb:{xs:11,md:4}}}>
  <Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between" gap={2} mb={3}><Stack direction="row" gap={1.5} alignItems="center"><ReceiptLongRoundedIcon color="primary"/><Box><Typography variant="h4" fontWeight={900}>Invoices</Typography><Typography color="text.secondary">Persistent invoice history for this workspace.</Typography></Box></Stack><Stack direction={{xs:"column",sm:"row"}} gap={1}><TextField size="small" label="Search invoices" value={search} onChange={e=>setSearch(e.target.value)}/><FormControl size="small" sx={{minWidth:150}}><InputLabel>Status</InputLabel><Select label="Status" value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(x=><MenuItem key={x} value={x}>{x||"All statuses"}</MenuItem>)}</Select></FormControl></Stack></Stack>
  {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{loading?<Box textAlign="center" py={8}><CircularProgress/></Box>:!sorted.length?<Alert severity="info">No generated invoices yet. Use Invoice Builder on a board to create one.</Alert>:<Stack gap={1.25}>{sorted.map(i=><Card key={i.id} variant="outlined" sx={{p:2,borderRadius:3}}><Stack direction={{xs:"column",md:"row"}} justifyContent="space-between" alignItems={{md:"center"}} gap={2}><Box><Typography fontWeight={900}>{i.invoice_number}</Typography><Typography>{i.client_name}</Typography><Typography variant="body2" color="text.secondary">{new Date(i.issue_date).toLocaleDateString()} → {new Date(i.due_date).toLocaleDateString()} · {i.created_by_name||"User"}</Typography></Box><Stack direction="row" gap={1} alignItems="center" flexWrap="wrap"><Typography fontWeight={900}>{money(i.total,i.currency)}</Typography><Chip label={i.status} color={i.status==="PAID"?"success":i.status==="OVERDUE"?"error":i.status==="SENT"?"info":"default"}/><Button onClick={()=>setSelected(i)}>View</Button>{i.pdf_file_id&&<Button component="a" href={getApiUrl(`/invoices/${i.id}/pdf`)} target="_blank">PDF</Button>}<Button onClick={()=>void duplicate(i)}>Duplicate</Button></Stack></Stack></Card>)}</Stack>}
  <Dialog open={Boolean(selected)} onClose={()=>setSelected(null)} fullWidth maxWidth="md"><DialogTitle>{selected?.invoice_number}</DialogTitle><DialogContent dividers>{selected&&<Stack gap={2}><Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between"><Box><Typography variant="overline">Client</Typography><Typography fontWeight={800}>{selected.client_name}</Typography></Box><Box><Typography variant="overline">Dates</Typography><Typography>{selected.issue_date} → {selected.due_date}</Typography></Box></Stack><Stack>{(selected.line_items||[]).map((item:any,index:number)=><Stack key={index} direction="row" justifyContent="space-between" sx={{py:1,borderBottom:"1px solid",borderColor:"divider"}}><Typography>{item.description} × {item.quantity}</Typography><Typography fontWeight={700}>{money(item.amount,selected.currency)}</Typography></Stack>)}</Stack><Box textAlign="right"><Typography>Subtotal: {money(selected.subtotal,selected.currency)}</Typography><Typography>Tax ({selected.tax_rate}%): {money(selected.tax_amount,selected.currency)}</Typography><Typography variant="h6" fontWeight={900}>Total: {money(selected.total,selected.currency)}</Typography></Box>{selected.notes&&<Alert severity="info">{selected.notes}</Alert>}</Stack>}</DialogContent><DialogActions sx={{flexWrap:"wrap"}}>{selected?.pdf_file_id&&<Button component="a" href={getApiUrl(`/invoices/${selected.id}/pdf`)} target="_blank">Download PDF</Button>}<Button onClick={()=>void duplicate(selected!)}>Duplicate</Button>{selected?.status==="DRAFT"&&<Button onClick={()=>void update("SENT")}>Mark Sent</Button>}{selected?.status!=="PAID"&&selected?.status!=="CANCELLED"&&<Button color="success" onClick={()=>void update("PAID")}>Mark Paid</Button>}{selected?.status!=="CANCELLED"&&<Button color="error" onClick={()=>void update("CANCELLED")}>Cancel</Button>}<Button onClick={()=>setSelected(null)}>Close</Button></DialogActions></Dialog>
 </Box>
}
