"use client";
import React from 'react';
import { Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, IconButton, InputLabel, MenuItem, Paper, Select, Stack, TextField, Typography } from '@mui/material';
import AddIcon from '@mui/icons-material/Add'; import ContentCopyIcon from '@mui/icons-material/ContentCopy'; import DeleteIcon from '@mui/icons-material/Delete'; import DragIndicatorIcon from '@mui/icons-material/DragIndicator'; import FullscreenIcon from '@mui/icons-material/Fullscreen';
import type { Column, Row } from '../../../types';
type Widget={id:string;type:string;title:string;columnId?:string;aggregation:string;size:'small'|'medium'|'large'};
const numberOf=(value:any)=>{const parsed=Number(String(value?.amount??value?.value??value??'').replace(/[^0-9.-]/g,''));return Number.isFinite(parsed)?parsed:0};
const defaultWidgets:Widget[]=[{id:'rows',type:'kpi',title:'Total rows',aggregation:'count',size:'small'},{id:'status',type:'status',title:'Status overview',aggregation:'count',size:'medium'},{id:'activity',type:'activity',title:'Recent activity',aggregation:'count',size:'medium'}];
export default function DashboardBoardView({tableId,rows,columns}:{tableId:string;rows:Row[];columns:Column[]}){
 const storageKey=`smart-manage:dashboard:${tableId}`; const [widgets,setWidgets]=React.useState<Widget[]>(defaultWidgets); const [open,setOpen]=React.useState(false); const [full,setFull]=React.useState(false); const [draft,setDraft]=React.useState<Widget>({id:'',type:'kpi',title:'',aggregation:'count',size:'small'}); const drag=React.useRef<number|null>(null);
 React.useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(Array.isArray(saved)&&saved.length)setWidgets(saved)}catch{}},[storageKey]); React.useEffect(()=>{localStorage.setItem(storageKey,JSON.stringify(widgets))},[storageKey,widgets]);
 const metric=(w:Widget)=>{if(w.aggregation==='count')return rows.length;const vals=rows.map(r=>numberOf(r.values?.[w.columnId||'']));if(w.aggregation==='sum')return vals.reduce((a,b)=>a+b,0);if(w.aggregation==='average')return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0;return rows.length};
 const add=()=>{setWidgets([...widgets,{...draft,id:crypto.randomUUID(),title:draft.title||'New widget'}]);setOpen(false)}; const reorder=(to:number)=>{if(drag.current==null||drag.current===to)return;const next=[...widgets];const [item]=next.splice(drag.current,1);next.splice(to,0,item);setWidgets(next);drag.current=null};
 return <Box sx={{position:full?'fixed':'relative',inset:full?0:'auto',zIndex:full?1500:'auto',bgcolor:'background.default',p:full?3:0,overflow:'auto'}}><Stack direction="row" justifyContent="space-between" alignItems="center" mt={4} mb={3}><Box><Typography variant="h5" fontWeight={900}>Dashboard Builder</Typography><Typography color="text.secondary">{widgets.length} widgets · live board data</Typography></Box><Stack direction="row" gap={1}><Button startIcon={<AddIcon/>} variant="contained" onClick={()=>{setDraft({id:'',type:'kpi',title:'',aggregation:'count',size:'small'});setOpen(true)}}>Add widget</Button><IconButton aria-label="Toggle fullscreen" onClick={()=>setFull(!full)}><FullscreenIcon/></IconButton></Stack></Stack><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(12,1fr)'},gap:2}}>{widgets.map((w,index)=><Paper draggable onDragStart={()=>{drag.current=index}} onDragOver={(e)=>e.preventDefault()} onDrop={()=>reorder(index)} key={w.id} sx={{p:2.5,borderRadius:3,border:'1px solid',borderColor:'divider',gridColumn:{md:`span ${w.size==='large'?12:w.size==='medium'?6:4}`},minHeight:w.size==='large'?220:150}}><Stack direction="row" justifyContent="space-between"><Stack direction="row" alignItems="center"><DragIndicatorIcon color="disabled"/><Typography fontWeight={900}>{w.title}</Typography></Stack><Box><IconButton size="small" aria-label={`Duplicate ${w.title}`} onClick={()=>setWidgets([...widgets,{...w,id:crypto.randomUUID(),title:`${w.title} copy`}])}><ContentCopyIcon fontSize="small"/></IconButton><IconButton size="small" aria-label={`Delete ${w.title}`} onClick={()=>setWidgets(widgets.filter(x=>x.id!==w.id))}><DeleteIcon fontSize="small"/></IconButton></Box></Stack><Typography sx={{fontSize:w.type==='kpi'?44:30,fontWeight:950,mt:2,color:'primary.main'}}>{metric(w).toLocaleString(undefined,{maximumFractionDigits:2})}</Typography><Typography color="text.secondary" textTransform="capitalize">{w.aggregation} · {w.type}</Typography></Paper>)}</Box>
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Add dashboard widget</DialogTitle><DialogContent><Stack gap={2} mt={1}><TextField label="Title" value={draft.title} onChange={(e)=>setDraft({...draft,title:e.target.value})}/><FormControl><InputLabel>Widget type</InputLabel><Select label="Widget type" value={draft.type} onChange={(e)=>setDraft({...draft,type:e.target.value})}>{['kpi','revenue','expenses','profit','status','activity','calendar','table','chart','map','progress','number','text','image','tasks','notifications','files'].map(t=><MenuItem key={t} value={t}>{t}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>Source column</InputLabel><Select label="Source column" value={draft.columnId||''} onChange={(e)=>setDraft({...draft,columnId:e.target.value})}><MenuItem value="">All rows</MenuItem>{columns.map(c=><MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>Aggregation</InputLabel><Select label="Aggregation" value={draft.aggregation} onChange={(e)=>setDraft({...draft,aggregation:e.target.value})}>{['count','sum','average'].map(a=><MenuItem key={a} value={a}>{a}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>Size</InputLabel><Select label="Size" value={draft.size} onChange={(e)=>setDraft({...draft,size:e.target.value as any})}>{['small','medium','large'].map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</Select></FormControl></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" onClick={add}>Add widget</Button></DialogActions></Dialog></Box>
}
