"use client";
import React from 'react';
import { Alert, Box, Button, Checkbox, FormControlLabel, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import type { Column } from '../../../types';

export default function FormBoardView({ columns, onSubmit }: { columns: Column[]; onSubmit: (values:Record<string,any>)=>Promise<void> }) {
  const fields=columns.filter((c)=>!['Formula','Created date','Updated date','Created by','Last updated by','Files','Image'].includes(c.type));
  const [values,setValues]=React.useState<Record<string,any>>({}); const [errors,setErrors]=React.useState<Record<string,string>>({}); const [sending,setSending]=React.useState(false); const [success,setSuccess]=React.useState(false);
  const submit=async()=>{const next:Record<string,string>={}; fields.forEach((c)=>{const v=values[c.id]; if(c.required&&(v===''||v==null))next[c.id]=`${c.name} is required`; if(c.type==='Email'&&v&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v)))next[c.id]='Enter a valid email';}); setErrors(next); if(Object.keys(next).length)return; setSending(true); setSuccess(false); try{await onSubmit(values);setValues({});setSuccess(true);}finally{setSending(false);}};
  return <Paper sx={{mt:4,p:{xs:2.5,md:4},maxWidth:760,mx:'auto',borderRadius:4,border:'1px solid',borderColor:'divider'}}><Typography variant="h5" fontWeight={900}>Board Submission Form</Typography><Typography color="text.secondary" mb={3}>Create a new row without leaving this view.</Typography>{success&&<Alert severity="success" sx={{mb:2}}>Submission created successfully.</Alert>}<Stack gap={2}>{fields.map((c)=>c.type==='Checkbox'?<FormControlLabel key={c.id} control={<Checkbox checked={Boolean(values[c.id])} onChange={(e)=>setValues({...values,[c.id]:e.target.checked})}/>} label={c.name}/>:<TextField key={c.id} label={c.name} required={Boolean(c.required)} type={['Email','Phone','Website','Numbers','Money'].includes(c.type)?(c.type==='Email'?'email':c.type==='Phone'?'tel':c.type==='Website'?'url':'number'):'text'} multiline={c.type==='LongText'} minRows={c.type==='LongText'?4:undefined} select={['Status','Dropdown','Priority','Country','Color','Rating'].includes(c.type)&&Boolean(c.options?.length)} value={values[c.id]??''} onChange={(e)=>setValues({...values,[c.id]:e.target.value})} error={Boolean(errors[c.id])} helperText={errors[c.id]}>{(c.options||[]).map((option)=><MenuItem key={option.value} value={option.value}>{option.value}</MenuItem>)}</TextField>)}</Stack><Box mt={3} display="flex" justifyContent="flex-end"><Button variant="contained" size="large" disabled={sending} onClick={submit}>{sending?'Submitting...':'Submit response'}</Button></Box></Paper>;
}
