"use client";
import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Alert, Box, Button, Card, CardActions, CardContent, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Divider, MenuItem, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import MapRoundedIcon from "@mui/icons-material/MapRounded";
import NavigationRoundedIcon from "@mui/icons-material/NavigationRounded";
import PhoneRoundedIcon from "@mui/icons-material/PhoneRounded";
import WarningAmberRoundedIcon from "@mui/icons-material/WarningAmberRounded";
import { authenticatedFetch, getApiUrl } from "../../apiUrl";

type DriverFile={id?:string;url:string;name:string;originalName?:string;type?:string;size?:number;uploadedAt?:string;category?:string};
type Trip = { id:string;tableId:string;tripNumber:string;name:string;status:string;pickupAddress:string;deliveryAddress:string;pickupLatitude?:number;pickupLongitude?:number;deliveryLatitude?:number;deliveryLongitude?:number;pickupDate?:string;deliveryDate?:string;truck?:string;trailer?:string;cargo?:string;contactPerson?:string;contactPhone?:string;distance?:number;instructions?:string;documents?:DriverFile[];activity?:Array<{text:string;time:string}> };
const completed=(trip:Trip)=>trip.status==="Delivered";
const destination=(trip:Trip)=>["Loaded","In Transit","At Delivery","Delivered"].includes(trip.status)?trip.deliveryAddress:trip.pickupAddress;
const internalMapUrl=(workspaceId:string,trip:Trip,navigation?:"pickup"|"delivery")=>`/driver-trips/?id=${encodeURIComponent(workspaceId)}&section=map&tripId=${encodeURIComponent(trip.id)}${navigation?`&navigation=${navigation}`:""}`;

export default function DriverTripsPage(){
  const searchParams=useSearchParams(),workspaceId=searchParams.get("id")||"",section=searchParams.get("section")||"trips",mapTripId=searchParams.get("tripId")||"";
  const [trips,setTrips]=useState<Trip[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState(0),[selected,setSelected]=useState<Trip|null>(null);
  const [uploadOpen,setUploadOpen]=useState(false),[uploading,setUploading]=useState(false),[uploadFile,setUploadFile]=useState<File|null>(null),[uploadCategory,setUploadCategory]=useState("trip"),[uploadTripId,setUploadTripId]=useState(""),[liters,setLiters]=useState(""),[pricePerLiter,setPricePerLiter]=useState(""),[odometer,setOdometer]=useState(""),[amount,setAmount]=useState("");
  const load=async()=>{if(!workspaceId){setError("Workspace is missing");setLoading(false);return}try{const response=await authenticatedFetch(getApiUrl(`logistics/driver/trips?workspaceId=${encodeURIComponent(workspaceId)}`));const text=await response.text();const data=text?JSON.parse(text):{};response.ok?(setTrips(data.trips||[]),setError("")):(setTrips([]),setError(data.error||`Unable to load trips (${response.status})`))}catch(error){setTrips([]);setError(error instanceof Error?error.message:"Unable to load trips")}finally{setLoading(false)}};
  useEffect(()=>{void load();const timer=window.setInterval(load,15000);return()=>window.clearInterval(timer)},[workspaceId]);
  const visible=useMemo(()=>trips.filter(trip=>tab===3?completed(trip):tab===0?!completed(trip):tab===1?Boolean(trip.pickupDate&&new Date(trip.pickupDate).toDateString()===new Date().toDateString()):!completed(trip)),[trips,tab]);
  const updateStatus=async(trip:Trip,status:string)=>{const confirmed=!["Loaded","Delivered"].includes(status)||window.confirm(`Confirm status: ${status}?`);if(!confirmed)return;const response=await authenticatedFetch(getApiUrl("logistics/driver/trips"),{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspaceId,tripId:trip.id,status,confirmed})});const data=await response.json();if(response.ok){setTrips(items=>items.map(item=>item.id===trip.id?data.trip:item));setSelected(data.trip)}else setError(data.error||"Status could not be saved")};
  const submitDocument=async()=>{if(!uploadFile||!uploadTripId)return;setUploading(true);setError("");try{const formData=new FormData();formData.append("file",uploadFile);const uploadResponse=await authenticatedFetch(getApiUrl("upload"),{method:"POST",body:formData});const uploaded=await uploadResponse.json();if(!uploadResponse.ok||!uploaded?.url)throw new Error(uploaded?.error||"File upload failed");const response=await authenticatedFetch(getApiUrl("logistics/driver/documents"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspaceId,tripId:uploadTripId,category:uploadCategory,file:uploaded,liters,pricePerLiter,odometer,amount})});const data=await response.json();if(!response.ok)throw new Error(data?.error||"Document could not be saved");setUploadOpen(false);setUploadFile(null);setLiters("");setPricePerLiter("");setOdometer("");setAmount("");await load()}catch(error){setError(error instanceof Error?error.message:"Upload failed")}finally{setUploading(false)}};
  if(loading)return <Box sx={{display:"grid",placeItems:"center",minHeight:"60vh"}}><CircularProgress/></Box>;
  const mapTrip=trips.find((trip)=>trip.id===mapTripId)||trips[0];
  if(section==="map"&&mapTrip)return <Box sx={{maxWidth:1100,mx:"auto",p:{xs:2,md:4},pb:12}}><Stack direction="row" justifyContent="space-between" alignItems="center" mb={2}><Box><Typography variant="h4" fontWeight={900}>Trip Map</Typography><Typography color="text.secondary">{mapTrip.tripNumber} · {searchParams.get("navigation")==="delivery"?"Destination":"Pickup and delivery"}</Typography></Box><Button href={`/driver-trips/?id=${encodeURIComponent(workspaceId)}`}>Back to My Trips</Button></Stack><Card sx={{borderRadius:4,overflow:"hidden"}}><Box sx={{height:{xs:420,md:580},background:"linear-gradient(135deg,#dbeafe,#dcfce7)",display:"grid",placeItems:"center",p:3}}><Stack spacing={2} sx={{maxWidth:700,width:"100%"}}><Typography variant="h5" fontWeight={900}>Map View</Typography><Card variant="outlined" sx={{p:2,borderRadius:3}}><Typography variant="overline">Pickup</Typography><Typography fontWeight={800}>{mapTrip.pickupAddress||"Address missing"}</Typography></Card><Card variant="outlined" sx={{p:2,borderRadius:3}}><Typography variant="overline">Destination</Typography><Typography fontWeight={800}>{mapTrip.deliveryAddress||"Address missing"}</Typography></Card><Alert severity={mapTrip.pickupLatitude&&mapTrip.deliveryLatitude?"success":"info"}>Route stays inside Smart Manage. Saved coordinates are used when available.</Alert></Stack></Box></Card></Box>;
  return <Box sx={{maxWidth:1100,mx:"auto",p:{xs:2,md:4},pb:{xs:12,md:4}}}>
    <Stack direction="row" justifyContent="space-between" alignItems="center" gap={2}><Typography variant="h4" fontWeight={900}>{section==="documents"?"My Documents":"My Trips"}</Typography><Button variant="contained" onClick={()=>{setUploadTripId(trips[0]?.id||"");setUploadOpen(true)}} disabled={!trips.length}>Upload Document</Button></Stack>
    <Typography color="text.secondary" sx={{mb:2}}>Only trips assigned to your account are shown.</Typography>
    {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}
    {section!=="documents"&&<Tabs value={tab} onChange={(_,value)=>setTab(value)} variant="scrollable" sx={{mb:2}}><Tab label="Current Trip"/><Tab label="Today"/><Tab label="Upcoming"/><Tab label="Completed"/></Tabs>}
    {section==="documents"&&<Stack spacing={2} sx={{my:2}}>{trips.flatMap((trip)=>(trip.documents||[]).map((file)=><Card key={`${trip.id}-${file.url}`} variant="outlined" sx={{p:2,borderRadius:3}}><Typography fontWeight={900}>{file.name}</Typography><Typography variant="body2" color="text.secondary">{trip.tripNumber} · {file.category||"Trip document"}</Typography><Button href={file.url} target="_blank" sx={{mt:1}}>Open Document</Button></Card>))}{!trips.some((trip)=>trip.documents?.length)&&<Alert severity="info">No uploaded documents yet.</Alert>}</Stack>}
    {section!=="documents"&&<>
    <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"repeat(2,1fr)"},gap:2}}>
      {visible.map(trip=><Card key={trip.id} variant="outlined" sx={{borderRadius:4}}>
        <CardContent>
          <Stack direction="row" justifyContent="space-between" gap={1}><Typography variant="h6" fontWeight={900}>{trip.tripNumber}</Typography><Chip label={trip.status} color={completed(trip)?"success":"primary"} size="small"/></Stack>
          <Divider sx={{my:2}}/><Typography variant="overline" color="text.secondary">Pickup</Typography><Typography fontWeight={700}>{trip.pickupAddress||"Address missing"}</Typography>
          <Typography variant="overline" color="text.secondary" sx={{display:"block",mt:1.5}}>Delivery</Typography><Typography fontWeight={700}>{trip.deliveryAddress||"Address missing"}</Typography>
          <Stack spacing={0.6} sx={{mt:2}}><Typography><b>Date:</b> {trip.pickupDate?new Date(trip.pickupDate).toLocaleString():"—"}</Typography><Typography><b>Truck:</b> {trip.truck||"—"}{trip.trailer?` · ${trip.trailer}`:""}</Typography><Typography><b>Cargo:</b> {trip.cargo||"—"}</Typography>{trip.distance&&<Typography><b>Distance:</b> {trip.distance} km</Typography>}</Stack>
        </CardContent>
        <CardActions sx={{flexWrap:"wrap",p:2,pt:0}}><Button onClick={()=>setSelected(trip)}>View Trip</Button><Button startIcon={<MapRoundedIcon/>} href={internalMapUrl(workspaceId,trip)}>Open Map</Button><Button startIcon={<NavigationRoundedIcon/>} href={internalMapUrl(workspaceId,trip,"pickup")}>Navigate to Pickup</Button><Button variant="contained" startIcon={<NavigationRoundedIcon/>} href={internalMapUrl(workspaceId,trip,"delivery")}>Go to Destination</Button><Button onClick={()=>navigator.clipboard.writeText(destination(trip))}>Copy Address</Button></CardActions>
      </Card>)}
    </Box>
    {!visible.length&&!error&&<Alert severity="info">No trips in this section.</Alert>}
    </>}
    <Dialog open={Boolean(selected)} onClose={()=>setSelected(null)} fullScreen={typeof window!=="undefined"&&window.innerWidth<600} fullWidth maxWidth="md">
      {selected&&<><DialogTitle><Stack direction="row" justifyContent="space-between"><span>{selected.tripNumber}</span><Chip label={selected.status}/></Stack></DialogTitle><DialogContent dividers><Stack spacing={2}>
        <section><Typography variant="h6" fontWeight={800}>Trip Summary</Typography><Typography>{selected.cargo||"No cargo description"}</Typography></section><Divider/>
        <section><Typography variant="h6" fontWeight={800}>Route Map</Typography><Alert severity={selected.pickupAddress&&selected.deliveryAddress?"info":"warning"}>{selected.pickupAddress} → {selected.deliveryAddress}</Alert><Button sx={{mt:1}} href={internalMapUrl(workspaceId,selected)} startIcon={<MapRoundedIcon/>}>Open Trips Map</Button></section>
        <section><Typography variant="h6" fontWeight={800}>Pickup Information</Typography><Typography>{selected.pickupAddress}</Typography><Typography>{selected.pickupDate?new Date(selected.pickupDate).toLocaleString():"—"}</Typography></section>
        <section><Typography variant="h6" fontWeight={800}>Delivery Information</Typography><Typography>{selected.deliveryAddress}</Typography><Typography>{selected.deliveryDate?new Date(selected.deliveryDate).toLocaleString():"—"}</Typography></section>
        <section><Typography variant="h6" fontWeight={800}>Assigned Vehicle</Typography><Typography>{selected.truck||"—"} {selected.trailer||""}</Typography></section>
        <section><Typography variant="h6" fontWeight={800}>Contacts</Typography><Typography>{selected.contactPerson||"—"}</Typography>{selected.contactPhone&&<Button href={`tel:${selected.contactPhone}`} startIcon={<PhoneRoundedIcon/>}>Call {selected.contactPhone}</Button>}</section>
        <section><Typography variant="h6" fontWeight={800}>Instructions</Typography><Typography>{selected.instructions||"No special instructions"}</Typography></section>
        <section><Typography variant="h6" fontWeight={800}>Update Status</Typography><Stack direction="row" flexWrap="wrap" gap={1} sx={{mt:1}}>{["Accepted","Going to Pickup","At Pickup","Loaded","In Transit","At Delivery","Delivered","Problem Reported"].map(status=><Button key={status} size="small" color={status==="Problem Reported"?"error":"primary"} variant={selected.status===status?"contained":"outlined"} startIcon={status==="Problem Reported"?<WarningAmberRoundedIcon/>:undefined} onClick={()=>updateStatus(selected,status)}>{status}</Button>)}</Stack></section>
        <section><Typography variant="h6" fontWeight={800}>Status Timeline</Typography>{selected.activity?.map((entry,index)=><Typography key={index} variant="body2" sx={{mt:1}}>{entry.text} · {new Date(entry.time).toLocaleString()}</Typography>)}</section>
      </Stack></DialogContent><DialogActions><Button onClick={()=>setSelected(null)}>Close</Button></DialogActions></>}
    </Dialog>
    <Dialog open={uploadOpen} onClose={()=>!uploading&&setUploadOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Upload Driver Document</DialogTitle><DialogContent><Stack spacing={2} sx={{mt:1}}><TextField select label="Trip" value={uploadTripId} onChange={(event)=>setUploadTripId(event.target.value)}>{trips.map((trip)=><MenuItem key={trip.id} value={trip.id}>{trip.tripNumber} · {trip.pickupAddress} → {trip.deliveryAddress}</MenuItem>)}</TextField><TextField select label="Document type" value={uploadCategory} onChange={(event)=>setUploadCategory(event.target.value)}><MenuItem value="trip">Trip document / CMR</MenuItem><MenuItem value="fuel">Fuel receipt</MenuItem><MenuItem value="expense">Expense invoice / receipt</MenuItem></TextField>{uploadCategory==="fuel"&&<><TextField label="Liters" type="number" value={liters} onChange={(event)=>setLiters(event.target.value)}/><TextField label="Price per liter" type="number" value={pricePerLiter} onChange={(event)=>setPricePerLiter(event.target.value)}/><TextField label="Odometer KM" type="number" value={odometer} onChange={(event)=>setOdometer(event.target.value)}/></>}{uploadCategory==="expense"&&<TextField label="Amount" type="number" value={amount} onChange={(event)=>setAmount(event.target.value)}/>}<Button component="label" variant="outlined">{uploadFile?uploadFile.name:"Choose file"}<input hidden type="file" accept="image/*,.pdf,.doc,.docx,.xls,.xlsx" onChange={(event)=>setUploadFile(event.target.files?.[0]||null)}/></Button></Stack></DialogContent><DialogActions><Button onClick={()=>setUploadOpen(false)} disabled={uploading}>Cancel</Button><Button variant="contained" onClick={submitDocument} disabled={!uploadFile||!uploadTripId||uploading}>{uploading?"Uploading...":"Upload and save"}</Button></DialogActions></Dialog>
  </Box>;
}
